ImageSharing/ImageSharing/Areas/User/Controllers/UserHomeController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImageSharing.Models;
using ImageSharing.Models.EntityInfo;
using ImageSharing.DAL.Entity;
using ImageSharing.UserService;
using ImageSharing.TapeService;
using ImageSharing.PostService;
using ImageSharing.SubscriptionService;
using ImageSharing.CommentService;
using ImageSharing.FriendshipRequestService;
using ImageSharing.FriendshipService;
using ImageSharing.Models.InfoCreator;
using ImageSharing.Security;
using System.Threading;
using System.Globalization;
using ImageSharing.Culture;

namespace ImageSharing.Areas.User.Controllers
{
    public class UserHomeController : Controller
    {
        //
        // GET: /User/UserHome/
        UserServiceClient userClient = new UserServiceClient();
        TapeServiceClient tapeClient = new TapeServiceClient();
        PostServiceClient postClient = new PostServiceClient();
        SubscriptionServiceClient subClient = new SubscriptionServiceClient();
        CommentServiceClient commentClient = new CommentServiceClient();
        FriendshipServiceClient friendshipClient = new FriendshipServiceClient();
        FriendshipRequestServiceClient requestClient = new FriendshipRequestServiceClient();

        #region Actions
        public ActionResult Home()
        {
            int ID = int.Parse(HttpContext.Request.Cookies["ID"].Value);
            UserAccount user = userClient.GetUser(int.Parse(HttpContext.Request.Cookies["ID"].Value));
            UserAccountInfo userInfo = (UserAccountInfo)new UserAccountInfoCreator().Create(user, userClient, postClient, tapeClient, friendshipClient, commentClient, subClient);
            foreach (FriendInfo friend in userInfo.Friends)     //Adding friends posts
            {
                if (subClient.GetSubscriptions().Any(s => s.FollowerID == ID && s.UserID == friend.ID))
                {
                    Subscription sub = subClient.GetSubscriptions().First(s => s.FollowerID == ID && s.UserID == friend.ID);
                    IEnumerable<Post>posts=postClient.GetPosts().Where(p=>p.TapeID==tapeClient.GetTapes().First(t=>t.UserID==friend.ID).ID);
                    foreach (Post post in posts) if(post.DateTime>sub.DateTime)userInfo.Tape.Posts.Add((PostInfo)new PostInfoCreator().Create(post, userClient, postClient, tapeClient, friendshipClient, commentClient, subClient));
                }
            }

            for (int i = 0; i < userInfo.Tape.Posts.Count(); i++)//Sort
            {
                for (int j = userInfo.Tape.Posts.Count() - 1; j > 0; j--)
                {
                    if (i < j)
                    {
                        PostInfo iPost = userInfo.Tape.Posts[i];
                        PostInfo jPost = userInfo.Tape.Posts[j];
                        if (iPost.DateTime < jPost.DateTime)
                        {
                            PostInfo temp = iPost;
                            userInfo.Tape.Posts[i] = jPost;
                            userInfo.Tape.Posts[j] = temp;
                        }
                    }
                }
            }
            return View(userInfo);
        }
        public ActionResult FriendsPage()
        {
            int ID = int.Parse(HttpContext.Request.Cookies["ID"].Value);

            List<FriendInfo> friends = new List<FriendInfo>();
            List<UserAccount> userFriends = new List<UserAccount>();
            IEnumerable<Friendship> friendships = friendshipClient.GetFriendships().Where(f => f.User1ID == ID || f.User2ID == ID);
            foreach (Friendship f in friendships)
            {
                if (f.User1ID == ID) userFriends.Add(userClient.GetUser(f.User2ID));
                if (f.User2ID == ID) userFriends.Add(userClient.GetUser(f.User1ID));
            }
            foreach (UserAccount friend in userFriends) friends.Add((FriendInfo)new FriendInfoCreator().Create(friend, userClient, postClient, tapeClient, friendshipClient, commentClient, subClient));
            return View(friends);
        }
        public ActionResult AccountPage()
        {
            UserAccountInfo userInfo = (UserAccountInfo)new UserAccountInfoCreator().Create(userClient.GetUser(int.Parse(HttpContext.Request.Cookies["ID"].Value)), userClient, postClient, tapeClient, friendshipClient, commentClient, subClient);
            ChangeAccountModel accountModel = new ChangeAccountModel 
            {
                Name=userInfo.Name,
                Surname=userInfo.Surname,
                Email=userInfo.Email,
                Avatar=userInfo.AvatarName
            };
            accountModel.Password = "";
            return View(accountModel);
        }
        [HttpPost]
        public ActionResult ChangeAccountInfo(ChangeAccountModel accountInfo, HttpPostedFileBase Avatar)
        {
            UserAccountInfo userInfo = (UserAccountInfo)new UserAccountInfoCreator().Create(userClient.GetUser(int.Parse(HttpContext.Request.Cookies["ID"].Value)), userClient, postClient, tapeClient, friendshipClient, commentClient, subClient);
            if (userInfo.Name != accountInfo.Name && accountInfo.Name != "" && accountInfo.Name != null) userClient.ChangeName(userInfo.ID, accountInfo.Name);
            if (userInfo.Surname != accountInfo.Surname && accountInfo.Surname != "" && accountInfo.Surname != null) userClient.ChangeSurname(userInfo.ID, accountInfo.Surname);
            if (userInfo.Email != accountInfo.Email && accountInfo.Email != "" && accountInfo.Email != null) userClient.ChangeEmail(userInfo.ID, accountInfo.Email);
            if (userInfo.Password != accountInfo.Password && accountInfo.Password != "" && accountInfo.Password != null) userClient.ChangePassword(userInfo.ID, Scrambler.GetMD5Hash(accountInfo.Password));
            if (Avatar != null && userInfo.AvatarName != Avatar.FileName && Avatar.ContentType.ToLower().Split('/')[0] == "image")
            {
                string path = AppDomain.CurrentDomain.BaseDirectory + @"Content\AvatarImages\";
                string fileName = Path.GetFileName(Avatar.FileName);
                string rootPath = Path.Combine(path, fileName);
                if (fileName != null) Avatar.SaveAs(rootPath);

                userClient.ChangeAvatarPath(userInfo.ID, Avatar.FileName);
            }

            return RedirectToAction("AccountPage");
        }
        [HttpPost]
        public ActionResult UploadPost(HttpPostedFileBase upload, string Description)
        {
            if (upload.ContentType.ToLower().Split('/')[0] == "image")
            {
                int ID = int.Parse(HttpContext.Request.Cookies["ID"].Value);

                if (upload == null) return RedirectToAction("Home");
                string path = AppDomain.CurrentDomain.BaseDirectory + @"Content\UploadedImages\";
                string fileName = Path.GetFileName(upload.FileName);
                string rootPath = Path.Combine(path, fileName);
                if (fileName != null) upload.SaveAs(rootPath);

                IEnumerable<Post> posts = postClient.GetPosts();

                Post post = new Post
                {
                    AuthorID = int.Parse(HttpContext.Request.Cookies["ID"].Value),
                    DateTime = DateTime.Now,
                    ImagePath = fileName,
                    Description = Description,
                    TapeID = tapeClient.GetTapes().First(t => t.UserID == ID).ID
                };
                postClient.AddPost(post);
            }
            return RedirectToAction("Home");
        }
        public ActionResult Logout()
        {
            HttpContext.Response.Cookies["Role"].Value = "";
            HttpContext.Response.Cookies["ID"].Value = "";
            return RedirectToAction("LoginPage", "Home", new { area = "" });
        }
        public ActionResult MakeFriend(int id)
        {
            int ID = int.Parse(HttpContext.Request.Cookies["ID"].Value);
            if (!requestClient.GetRequests().Any(r => r.AskerID == id && r.DestinationID == ID))
            {
                IEnumerable<FriendshipRequest> requests = requestClient.GetRequests();
                FriendshipRequest request = new FriendshipRequest
                {
                    AskerID = ID,
                    DestinationID = id
                };
                requestClient.AddRequest(request);
            }

            if (requestClient.GetRequests().Any(r => r.AskerID == id && r.DestinationID == ID)) //При добавлении в друзья проверяем были ли от данного пользователя запросы и удаляем таковые
            {
                IEnumerable<FriendshipRequest> myRequests = requestClient.GetRequests().Where(r => r.AskerID == id && r.DestinationID == ID);
                foreach (FriendshipRequest request in myRequests)
                {
                    requestClient.RemoveRequest(request.ID);
                }
                friendshipClient.AddFriendship(new Friendship { User1ID = ID, User2ID = id });
            }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        public ActionResult RemoveRequest(int id)
        {
            int ID = int.Parse(HttpContext.Request.Cookies["ID"].Value);
            UserAccount currentUser = userClient.GetUser(ID);
            IEnumerable<FriendshipRequest> requests = requestClient.GetRequests().Where(r => r.AskerID == id);
            foreach (FriendshipRequest request in requests)
            {
                requestClient.RemoveRequest(request.ID);
            }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        public ActionResult RequestsPage()
        {
            int ID = int.Parse(HttpContext.Request.Cookies["ID"].Value);
            IEnumerable<FriendshipRequest> requests = requestClient.GetRequests().Where(r => r.DestinationID == ID);

            List<UserAccount> users = new List<UserAccount>();

ImageSharing/ImageSharing/Areas/User/Views/UserHome/AccountPage.cshtml
@model ImageSharing.Models.ChangeAccountModel

@{
    ViewBag.Title = "AccountPage";
}
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
    MessagesModel messages = new MessagesModel();
}
@section Body
{
    <div id="AccountContainer">
        @using (Html.BeginForm("ChangeAccountInfo", "UserHome", FormMethod.Post, new { area = "User", enctype = "multipart/form-data" }))
        {
            <div id="ChangeAvatarContainer">
                <img src="@Url.Content(@"..\..\..\..\Content\AvatarImages\" + Model.Avatar)" alt="Avatar" /><br />
                <input type="file" name="Avatar" /><br />
            </div><br />
            <br />
    
            @Html.LabelFor(m => m.Name)
            <input data-val="true" data-val-length="@Html.LabelFor(m => messages.MinLengthMessage).ToString() 3" data-val-length-max="100" data-val-length-min="3" id="Name" name="Name" type="text" value="@Model.Name" class="input-validation-error" />
            <span class="field-validation-valid" data-valmsg-for="Name" data-valmsg-replace="true"></span>
            <br /><br />
            @Html.LabelFor(m => m.Surname)
           <input data-val="true" data-val-length="@Html.LabelFor(m => messages.MinLengthMessage).ToString() 3" data-val-length-max="100" data-val-length-min="3" id="Surname" name="Surname" type="text" value="@Model.Surname" class="input-validation-error" />
            <span class="field-validation-valid" data-valmsg-for="Surname" data-valmsg-replace="true"></span>
            <br /><br />
            @Html.LabelFor(m => m.Email)
            <input data-val="true" data-val-length="@Html.LabelFor(m => messages.MinLengthMessage).ToString() 3" data-val-length-max="100" data-val-length-min="3" id="Email" name="Email" type="text" value="@Model.Email" class="input-validation-error" />
            <span class="field-validation-valid" data-valmsg-for="Email" data-valmsg-replace="true"></span>
            <br /><br />
            @Html.LabelFor(m => m.Password)
            <input data-val="true" data-val-length="@Html.LabelFor(m => messages.MinLengthMessage).ToString() 6" data-val-length-max="100" data-val-length-min="6" id="Password" name="Password" type="password" value="" class="input-validation-error" />
            <span class="field-validation-valid" data-valmsg-for="Password" data-valmsg-replace="true"></span>
            <br /><br />
            <div class="ReferenceContainer">
            <a href="javascript:{}" onclick="$('#AccountContainer>form').submit(); return false;">
                <div>
                    @Html.LabelFor(m => action.Save)
                </div>
            </a>
        </div>
        }
    </div>
    @Scripts.Render("~/bundles/jqueryval")
}

ImageSharing/ImageSharing/Areas/User/Views/UserHome/Comments.cshtml
@model List<ImageSharing.Models.EntityInfo.CommentInfo>

@foreach (ImageSharing.Models.EntityInfo.CommentInfo comment in Model)
{
    <div id="PopupPostCommentContainer">
        @comment.Text
    </div>
}

ImageSharing/ImageSharing/Areas/User/Views/UserHome/Descriptions.cshtml
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
}
<input type="text" name="Description" value ="@Model" />
<div class="ReferenceContainer">
    <a href="javascript:{}" onclick="$('#PopupPostUserInfoContainer>form').submit(); return false;">
        <div>
            @Html.LabelFor(m => action.Change)
        </div>
    </a>
</div>

ImageSharing/ImageSharing/Areas/User/Views/UserHome/FriendsPage.cshtml
@model IEnumerable<ImageSharing.Models.EntityInfo.FriendInfo>
@{
    ViewBag.Title = "Friends";
}
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
}
@section Body
{
<div id="FriendsContainer">
    <div id="FriendsNavigationContainer">
        <div class="ReferenceContainer">
            <a href="@Url.Action("RequestsPage","UserHome",new {area="User"})">
               <div>
                   @Html.LabelFor(m => action.Requests)
               </div>
            </a>
        </div>
    </div>
    @using(Html.BeginForm("SearchFriends","UserHome"))
    {
        <input type="text" name="searchString" />
        <div class="ReferenceContainer">
                <a href="javascript:{}" onclick="$('#FriendsContainer>form').submit(); return false;">
                    <div>
                        @Html.LabelFor(m => action.Search)
                    </div>
                </a>
            </div>
    }
    <div id="UsersContainer">
        @foreach(ImageSharing.Models.EntityInfo.FriendInfo friend in Model)
        {
            <div id="UserInfoContainer">
                <div id="AvatarImageContainer">
                    <img src="@Url.Content(@"..\..\..\..\Content\AvatarImages\"+friend.AvatarPath)" alt="Avatar"/>
                </div>
                <div id="NickContainer">
                    <a href="@Url.Action("UserPage", "Home", new { area = "", id = friend.ID })">
                        @friend.Surname @friend.Name
                    </a>
                </div>
            </div>
        }
        <h2>@ViewBag.SearchResult</h2>
    </div>
</div>
}

ImageSharing/ImageSharing/Areas/User/Views/UserHome/Home.cshtml
@model ImageSharing.Models.EntityInfo.UserAccountInfo

@{
    ViewBag.Title = "Home";
}
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
    MessagesModel messages = new MessagesModel();
}
@section Body{
    
    <div id="AvatarContainer">
        <div id="AvatarImageContainer">
            <img src="@Url.Content(@"..\..\..\..\Content\AvatarImages\"+Model.AvatarName)" alt="Avatar" />
        </div>
        <div id="NickContainer">
            @Model.Surname @Model.Name (@Html.LabelFor(m=>messages.IdentifierMessage))
        </div>
    </div>
    <div id="TapeContainer">
        <div id="AddPostContainer">
            @using (Html.BeginForm("UploadPost", "UserHome", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="file" name="upload" multiple />
                @Html.LabelFor(m=>messages.Description) <input type="text" name="Description" />
                <div class="ReferenceContainer">
                    <a href="javascript:{}" onclick="$('#AddPostContainer>form').submit(); return false;">
                        <div>
                            @Html.LabelFor(m => action.Upload)
                        </div>
                    </a>
                </div>
            }
        </div>
        @foreach (ImageSharing.Models.EntityInfo.PostInfo post in Model.Tape.Posts)
        {
            <div id="PostContainer">
                <div id="PostImageContainer" onclick="ShowPopup(@post.ID);">
                    <img src="@Url.Content(@"..\..\..\..\Content\UploadedImages\" + post.ImageName)" alt="Image"/>
                </div>
                <div id="PostDescriptionContainer">
                    @post.Author.Surname @post.Author.Name @post.DateTime.ToShortDateString() @post.DateTime.ToShortTimeString()
                </div>
                <div id="DeleteButton_@post.ID">
                    @using (Html.BeginForm("RemovePost", "UserHome", new { area = "User", id = post.ID }))
                    {
                        <div class="ReferenceContainer">
                            <a href="javascript:{}" onclick="$('#DeleteButton_@post.ID>form').submit(); return false;">
                                <div>
                                    @Html.LabelFor(m => action.Delete)
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>
            <div id="PopupPostContainer_@post.ID" class="table-responsive" style="display:none;">
                <div id="PopupPostImageContainer">
                    <img src="@Url.Content(@"..\..\..\..\Content\UploadedImages\" + post.ImageName)" alt="Image"/>
                </div>
                <div id="PopupPostUserInfoContainer">
                    @post.Author.Surname @post.Author.Name @post.DateTime.ToShortDateString() @post.DateTime.ToShortTimeString()<br />
                    <br />
                    @if (post.Author.ID == int.Parse(HttpContext.Current.Request.Cookies["ID"].Value))
                    {
                        var descriptionsOptions = new AjaxOptions()
                        {
                            UpdateTargetId = "PopupPostDescriptionContainer_" + post.ID,
                            Url = Url.Action("Descriptions", "UserHome", new { area = "User", id = post.ID }),
                        };
                        using (Ajax.BeginForm(descriptionsOptions))
                        {
                        <div id="PopupPostDescriptionContainer_@post.ID">
                            @Html.Action("Descriptions", "UserHome", new { area = "User", id = post.ID })
                        </div>
                        }
                    }
                    else
                    {@post.Description<br />}
                    <br />
                    <br />
                </div>

                <div id="PopupPostCommentsContainer">
                    <div id="PopupPostAddCommentContainer_@post.ID">
                        @{
                            var commentsOptions = new AjaxOptions()
                            {
                                UpdateTargetId = "CommentsContainer_" + post.ID,
                                Url = Url.Action("Comments", "UserHome", new { area = "User", id = post.ID }),
                            };
                        }
                        @using (Ajax.BeginForm(commentsOptions))
                        {
                            <input type="text" name="PostID" value="@post.ID" style="display:none;" />
                            <input type="text" name="Comment" placeholder="" />
                            <div class="ReferenceContainer">
                                <a href="javascript:{}" onclick="$('#PopupPostAddCommentContainer_@post.ID>form').submit(); return false;">
                                    <div>
                                        @Html.LabelFor(m => action.Send)
                                    </div>
                                </a>
                            </div>
                            
                            <div id="CommentsContainer_@post.ID">
                                @Html.Action("Comments", "UserHome", new { area = "User", id = post.ID })
                            </div>
                        }
                    </div>

                </div>
            </div>
        }
    </div>
    
    <script type="text/javascript">
        function ShowPopup(id) {
            $("#PopupPostContainer_" + id.toString()).dialog({
                height: window.innerHeight * 0.8,
                width: window.innerWidth * 0.8,
                modal: true,
            });
        }
    </script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

ImageSharing/ImageSharing/Areas/User/Views/UserHome/RequestsPage.cshtml
@model List<ImageSharing.Models.EntityInfo.UserAccountInfo>
@{
    ViewBag.Title = "RequestsPage";
}
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
}
@section Body
{
    <div id="UsersContainer">
        @foreach(ImageSharing.Models.EntityInfo.UserAccountInfo user in Model)
        {
            <div id="UserInfoContainer">
                <div id="AvatarImageContainer">
                    <img src="@Url.Content(@"..\..\..\..\Content\AvatarImages\"+user.AvatarName)" alt="Avatar"/>
                </div>
                <div id="NickContainer">
                    <a href="@Url.Action("UserPage", "Home", new { area = "", id = user.ID })">
                        @user.Surname @user.Name
                    </a>
                </div>
                <div id="MakeFriendButton">
                @using (Html.BeginForm("MakeFriend", "UserHome", new { area = "User", id = user.ID }))
                {
                    <div class="ReferenceContainer">
                        <a href="javascript:{}" onclick="$('#MakeFriendButton>form').submit(); return false;">
                            <div>
                                @Html.LabelFor(m => action.MakeFriend)
                            </div>
                        </a>
                    </div>
                }
                    </div>
                <div id="RemoveFriendButton">
                @using (Html.BeginForm("RemoveRequest", "UserHome", new { area = "User", id = user.ID }))
                {
                    <div class="ReferenceContainer">
                        <a href="javascript:{}" onclick="$('#RemoveFriendButton>form').submit(); return false;">
                            <div>
                                @Html.LabelFor(m => action.RemoveFriend)
                            </div>
                        </a>
                    </div>
                }
                    </div>
            </div>
        }
        <h2>@ViewBag.SearchResult</h2>
    </div>
}

ImageSharing/ImageSharing/Areas/User/Views/UserHome/SubscriptionsPage.cshtml
@model IEnumerable<ImageSharing.Models.EntityInfo.SubscriptionInfo>

@{
    ViewBag.Title = "SubscriptionsPage";
}
@using ImageSharing.Models;
@using ImageSharing.Models.EntityInfo;
@{
    ActionModel action = new ActionModel();
    SubscriptionInfo subInfo = new SubscriptionInfo();
}
@section Body
{
   
    <div id="SubscriptionsContainer">
        @using (Html.BeginForm("SearchSubscriptions", "UserHome"))
        {
            <input type="text" name="searchString" />
            <div class="ReferenceContainer">
                <a href="javascript:{}" onclick="$('#SubscriptionsContainer>form').submit(); return false;">
                    <div>
                        @Html.LabelFor(m => action.Search)
                    </div>
                </a>
            </div>
        }<br />
        <table id="SubscriptionsTable">
            <thead>
                <tr>
                    <td>@Html.LabelFor(m=>subInfo.UserName)</td>
                    <td>@Html.LabelFor(m=>subInfo.Surname)</td>
                    <td>@Html.LabelFor(m=>subInfo.PostsCount)</td>
                    <td>@Html.LabelFor(m=>action.Action)</td>
                </tr>
            </thead>
            @foreach (ImageSharing.Models.EntityInfo.SubscriptionInfo sub in Model)
            {
                <tr>
                    <td>@sub.UserName</td>
                    <td>@sub.Surname</td>
                    <td>@sub.PostsCount</td>
                    <td>
                        <div class="ReferenceContainer">
                            <a href="@Url.Action("Unfollow", "UserHome", new { area = "User", id = sub.friendId })">
                                <div>
                                    @Html.LabelFor(m => action.Unfollow)
                                </div>
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
}