ImageSharing/ImageSharing/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImageSharing.Models;
using ImageSharing.Models.EntityInfo;
using ImageSharing.DAL;
using ImageSharing.DAL.Entity;
using ImageSharing.UserService;
using ImageSharing.TapeService;
using ImageSharing.PostService;
using ImageSharing.SubscriptionService;
using ImageSharing.CommentService;
using ImageSharing.FriendshipRequestService;
using ImageSharing.FriendshipService;
using ImageSharing.Models.InfoCreator;
using ImageSharing.Security;
using ImageSharing.Areas.Admin.Models;
using System.IO;
using ImageSharing.Culture;

namespace ImageSharing.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        //
        // GET: /Admin/AdminHome/
        UserServiceClient userClient = new UserServiceClient();
        TapeServiceClient tapeClient = new TapeServiceClient();
        PostServiceClient postClient = new PostServiceClient();
        SubscriptionServiceClient subClient = new SubscriptionServiceClient();
        CommentServiceClient commentClient = new CommentServiceClient();
        FriendshipServiceClient friendshipClient = new FriendshipServiceClient();
        FriendshipRequestServiceClient requestClient = new FriendshipRequestServiceClient();

        public ActionResult AdministrationPage()
        {
            return View();
        }
        public ActionResult UsersConsolePage()
        {
            IEnumerable<UserAccount> users = userClient.GetUsers();
            UserAccountInfoCreator userCreator = new UserAccountInfoCreator();
            List<UserAccountInfo> userInfos = new List<UserAccountInfo>();
            foreach (UserAccount user in users)
                if (user.IsActivated)
                {
                    userInfos.Add((UserAccountInfo)userCreator.Create(user, userClient, postClient, tapeClient, friendshipClient, commentClient, subClient));
                }
            return PartialView(userInfos);
        }
        public ActionResult PostsConsolePage()
        {
            IEnumerable<Post> posts = postClient.GetPosts();
            PostInfoCreator postCreator = new PostInfoCreator();
            List<PostInfo> postInfos = new List<PostInfo>();
            foreach (Post post in posts) postInfos.Add((PostInfo)postCreator.Create(post, userClient, postClient, tapeClient, friendshipClient, commentClient, subClient));
            return PartialView(postInfos);
        }
        public ActionResult CommentsConsolePage()
        {
            IEnumerable<Post> posts = postClient.GetPosts();
            PostInfoCreator postCreator = new PostInfoCreator();
            List<PostInfo> postInfos = new List<PostInfo>();
            foreach (Post post in posts) postInfos.Add((PostInfo)postCreator.Create(post, userClient, postClient, tapeClient, friendshipClient, commentClient, subClient));
            return PartialView(postInfos);
        }
        [HttpPost]
        public ActionResult ChangeUsers(List<UserAccountInfo> users, List<HttpPostedFileBase> avatars)
        {
            int userCount = 0;
            if (users != null)
                foreach (UserAccountInfo userInfo in users)
                {
                    UserAccount user = userClient.GetUser(userInfo.ID);
                    if (userInfo.Surname != user.Surname) userClient.ChangeSurname(userInfo.ID, userInfo.Surname);
                    if (userInfo.Name != user.Name) userClient.ChangeName(userInfo.ID, userInfo.Name);
                    if (userInfo.Email != user.Email) userClient.ChangeEmail(userInfo.ID, userInfo.Email);
                    if (userInfo.Role != user.Role) userClient.ChangeRole(userInfo.ID, userInfo.Role);
                    if (avatars[userCount] != null && avatars[userCount].FileName != "" && userInfo.AvatarName != Path.GetFileName(avatars[userCount].FileName) && avatars[userCount].ContentType.ToLower().Split('/')[0] == "image")
                    {
                        string path = AppDomain.CurrentDomain.BaseDirectory + @"Content\AvatarImages\";
                        string fileName = Path.GetFileName(avatars[userCount].FileName);
                        string rootPath = Path.Combine(path, fileName);
                        if (fileName != null) avatars[userCount].SaveAs(rootPath);

                        userClient.ChangeAvatarPath(userInfo.ID, avatars[userCount].FileName);
                    }
                    userCount++;
                }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        [HttpPost]
        public ActionResult ChangePosts(List<PostInfo> posts, List<HttpPostedFileBase> images)
        {
            int postCount = 0;
            if (posts != null)
                foreach (PostInfo postInfo in posts)
                {

                    Post post = postClient.GetPost(postInfo.ID);
                    if (postInfo.DateTime != null && post.DateTime != postInfo.DateTime) postClient.ChangeDataTime(postInfo.ID, postInfo.DateTime);
                    if (postInfo.Description != null && post.Description != postInfo.Description) postClient.ChangeDescription(postInfo.ID, postInfo.Description);
                    if (images[postCount] != null && images[postCount].FileName != "" && postInfo.ImageName != Path.GetFileName(images[postCount].FileName) && images[postCount].ContentType.ToLower().Split('/')[0] == "image")
                    {
                        string path = AppDomain.CurrentDomain.BaseDirectory + @"Content\UploadedImages\";
                        string fileName = Path.GetFileName(images[postCount].FileName);
                        string rootPath = Path.Combine(path, fileName);
                        if (fileName != null) images[postCount].SaveAs(rootPath);

                        postClient.ChangeImagePath(postInfo.ID, images[postCount].FileName);
                    }
                    postCount++;
                }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        public ActionResult ChangeComments(List<CommentInfo> comments)
        {
            if (comments != null)
                foreach (CommentInfo commentInfo in comments)
                {
                    Comment comment = commentClient.GetComment(commentInfo.ID);
                    if (comment.Text != commentInfo.Text) commentClient.ChangeText(commentInfo.ID, commentInfo.Text);
                }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }

        public ActionResult DeleteUser(int id)
        {
            IEnumerable<Friendship> deletedFriendships = null;
            if (friendshipClient.GetFriendships().Any(f => f.User1ID == id || f.User2ID == id))
            {
                deletedFriendships = friendshipClient.GetFriendships().Where(f => f.User1ID == id || f.User2ID == id);
                foreach (Friendship friendship in deletedFriendships) friendshipClient.RemoveFriendship(friendship.ID); //deleting frienships
            }

            IEnumerable<FriendshipRequest> deletedRequests = null;
            if (requestClient.GetRequests().Any(r => r.AskerID == id || r.DestinationID == id))
            {
                deletedRequests = requestClient.GetRequests().Where(r => r.AskerID == id || r.DestinationID == id);
                foreach (FriendshipRequest request in deletedRequests) requestClient.RemoveRequest(request.ID);         //deleting requests
            }

            IEnumerable<Subscription> deletedSubs = null;
            if (subClient.GetSubscriptions().Any(s => s.UserID == id || s.FollowerID == id))
            {
                deletedSubs = subClient.GetSubscriptions().Where(s => s.UserID == id || s.FollowerID == id);
                foreach (Subscription sub in deletedSubs) subClient.RemoveSubscription(sub.ID);                     //deleting subs
            }

            Tape deletedTape = tapeClient.GetTapes().First(t => t.UserID == id);

            IEnumerable<Post> deletedPosts = null;
            if (postClient.GetPosts().Any(p => p.TapeID == deletedTape.ID))
            {
                deletedPosts = postClient.GetPosts().Where(p => p.TapeID == deletedTape.ID);
            }

            IEnumerable<Comment> deletedComments = null;
            if (deletedPosts != null)
                foreach (Post post in deletedPosts)
                {
                    if (commentClient.GetComments().Any(c => c.PostID == post.ID)) deletedComments = commentClient.GetComments().Where(c => c.PostID == post.ID);//Deleting comments
                }
            if (deletedComments != null) foreach (Comment comment in deletedComments) commentClient.RemoveComment(comment.ID);

            if (deletedPosts != null)
                foreach (Post post in deletedPosts) postClient.RemovePost(post.ID);                                         //deleting posts
            tapeClient.RemoveTape(deletedTape.ID);                                                                      //deleting tape






            UserAccount deletedUser = userClient.GetUser(id);
            userClient.RemoveUser(id);                                                                                  //deleting user

            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        public ActionResult DeletePost(int id)
        {
            IEnumerable<Comment> deletedComments = null;
            if (commentClient.GetComments().Any(c => c.PostID == id))
            {
                deletedComments = commentClient.GetComments().Where(c => c.PostID == id);
                foreach (Comment comment in deletedComments) commentClient.RemoveComment(comment.ID);
            }

            postClient.RemovePost(id);
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        public ActionResult DeleteComment(int id)
        {
            commentClient.RemoveComment(id);

ImageSharing/ImageSharing/Areas/Admin/Views/AdminHome/AdministrationPage.cshtml
@{
    ViewBag.Title = "AdministrationPage";
}
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
}
@section Body{
    <div id="AdministrationContainer">
        <div id="AdministrationNavigationContainer">
            <div id="AdministrationNavigationRow">
                <div class="AdministrationNavigationButtonContainer">
                    @{
                        var usersOptions = new AjaxOptions()
                            {
                                UpdateTargetId = "AdministrationConsoleContainer",
                                Url = Url.Action("UsersConsolePage", "AdminHome", new { area = "Admin" }),
                            };
                        <div id="UsersButton">
                            @using (Ajax.BeginForm(usersOptions))
                            {
                                <div class="ReferenceContainer">
                                    <a href="javascript:{}" onclick="$('#UsersButton>form').submit(); return false;">
                                        <div>
                                            @Html.LabelFor(m => action.Users)
                                        </div>
                                    </a>
                                </div>
                            }
                        </div>
                    }
                </div>
                <div class="AdministrationNavigationButtonContainer">
                    @{
                        var postsOptions = new AjaxOptions()
                            {
                                UpdateTargetId = "AdministrationConsoleContainer",
                                Url = Url.Action("PostsConsolePage", "AdminHome", new { area = "Admin" }),
                            };
                        <div id="PostsButton">
                            @using (Ajax.BeginForm(postsOptions))
                            {
                                <div class="ReferenceContainer">
                                    <a href="javascript:{}" onclick="$('#PostsButton>form').submit(); return false;">
                                        <div>
                                            @Html.LabelFor(m => action.Posts)
                                        </div>
                                    </a>
                                </div>
                            }
                        </div>
                    }
                </div>
                <div class="AdministrationNavigationButtonContainer">
                    @{
                        var commentsOptions = new AjaxOptions()
                            {
                                UpdateTargetId = "AdministrationConsoleContainer",
                                Url = Url.Action("CommentsConsolePage", "AdminHome", new { area = "Admin" }),
                            };
                        <div id="CommentsButton">
                            @using (Ajax.BeginForm(commentsOptions))
                            {
                                <div class="ReferenceContainer">
                                    <a href="javascript:{}" onclick="$('#CommentsButton>form').submit(); return false;">
                                        <div>
                                            @Html.LabelFor(m => action.Comments)
                                        </div>
                                    </a>
                                </div>
                        }
                        </div>
                    }
                </div>
            </div>
        </div>
        <div id="AdministrationConsoleContainer">
            @Html.Action("UsersConsolePage", "AdminHome", new { area = "Admin" })
        </div>
    </div>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
}

ImageSharing/ImageSharing/Areas/Admin/Views/AdminHome/CommentsConsolePage.cshtml
@model List<ImageSharing.Models.EntityInfo.PostInfo>
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
    MessagesModel messages = new MessagesModel();
}
<div id="CommentsConsoleContainer">
    @using (Html.BeginForm("ChangeComments", "AdminHome"))
    {
        <table id="AdminConsoleGrid">
            <thead>
                <tr>
                    <th>@Html.LabelFor(m => Model[0].PostID)</th>
                    <th>ID</th>
                    <th>@Html.LabelFor(m => Model[0].Comments.ToList()[0].Text)</th>
                </tr>
            </thead>
            @{var count = 0;}
            @foreach (ImageSharing.Models.EntityInfo.PostInfo post in Model)
            {
                for (int c = 0; c < post.Comments.Count(); c++)
                {
                <tr>
                    <td>
                        <input type="text" readonly="true" value="@post.ID" /></td>
                    <td>
                        <input type="text" value="@post.Comments.ToList()[c].ID" name="comments[@count].ID" readonly="true" /></td>
                    <td>
                        <input type="text" value="@post.Comments.ToList()[c].Text" name="comments[@count].Text" /></td>
                    <td>
                        
                        <div class="ReferenceContainer">
                            <a href="@Url.Action("DeleteComment", "AdminHome", new { area = "Admin", id = post.Comments.ToList()[c].ID })">
                                <div>
                                    @Html.LabelFor(m => action.Delete)
                                </div>
                            </a>
                        </div>
                    </td>
                </tr> 
                      count++;
                  }
              }
        </table>
            
        <div class="ReferenceContainer">
            <a href="javascript:{}" onclick="$('#CommentsConsoleContainer>form').submit(); return false;">
                <div>
                    @Html.LabelFor(m => action.Save)
                </div>
            </a>
        </div>
        
         <script type="text/javascript">

             var grid = document.getElementById('AdminConsoleGrid');

             $("#AdminConsoleGrid>thead>tr>th>label").click(function (e) {
                 sortGrid($(this.parentElement).index());
             });

             grid.onclick = function (e) {
                 if (e.target.tagName != 'TH') return;
                 sortGrid(e.target.cellIndex);
             };

             function sortGrid(colNum) {
                 var tbody = grid.getElementsByTagName('tbody')[0];

                 var rowsArray = [].slice.call(tbody.rows);

                 var compare;

                 compare = function (rowA, rowB) {
                     return rowA.cells[colNum].innerHTML > rowB.cells[colNum].innerHTML ? 1 : -1;

                 }
                 rowsArray.sort(compare);

                 grid.removeChild(tbody);

                 for (var i = 0; i < rowsArray.length; i++) {
                     tbody.appendChild(rowsArray[i]);
                 }

                 grid.appendChild(tbody);
             }
        </script>
    }
    <div id="AdministrationConsoleAddCommentContainer">
        @using (Html.BeginForm("AddComment", "AdminHome", new { area = "Admin" }))
        {
            @Html.AntiForgeryToken()
            <table>
                <thead>
                    <tr>
                        <td>@Html.LabelFor(m => Model[0].PostID)</td>
                        <td>@Html.LabelFor(m => Model[0].Comments.ToList()[0].Text)</td>
                    </tr>
                </thead>
                <tr>
                    <td>
                        <input data-val="true" data-val-required="@Html.LabelFor(m => messages.FieldRequiredMessage).ToString()" id="PostID" name="PostID" type="text" value="" class="input-validation-error" /><br />
                        <span class="field-validation-valid" data-valmsg-for="PostID" data-valmsg-replace="true"></span>
                    </td>
                    <td>
                        <input data-val="true" data-val-required="@Html.LabelFor(m => messages.FieldRequiredMessage).ToString()" id="Text" name="Text" type="text" value="" class="input-validation-error" /><br />
                        <span class="field-validation-valid" data-valmsg-for="Text" data-valmsg-replace="true"></span>
                    </td>
                    <td>
                        <div class="ReferenceContainer">
                            <a href="javascript:{}" onclick="$('#AdministrationConsoleAddCommentContainer>form').submit(); return false;">
                                <div>
                                    @Html.LabelFor(m => action.Add)
                                </div>
                            </a>
                        </div>
                    </td>
                </tr>
            </table>
        }
        <script type="text/javascript">
            function ValidateIntValue(event) {
                if (event.keyCode <= 48 || event.keyCode >= 57) {
                    $("#PostID").val("");
                }
            }
            $(PostID).keyup(ValidateIntValue);
        </script>
    </div>
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
</div>

ImageSharing/ImageSharing/Areas/Admin/Views/AdminHome/PostsConsolePage.cshtml
@model List<ImageSharing.Models.EntityInfo.PostInfo>
@using ImageSharing.Models;
@{
    ActionModel action = new ActionModel();
    MessagesModel messages = new MessagesModel();
}
<div id="PostsConsoleContainer">
    @using (Html.BeginForm("ChangePosts", "AdminHome", FormMethod.Post, new { area = "Admin", enctype = "multipart/form-data" }))
    {
        <table id="AdminConsoleGrid">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>@Html.LabelFor(m => Model[0].Author)</th>
                    <th>@Html.LabelFor(m => Model[0].DateTime)</th>
                    <th>@Html.LabelFor(m => Model[0].Description)</th>
                    <th>@Html.LabelFor(m => Model[0].ImageName)</th>
                </tr>
            </thead>
            @for (int i = 0; i < Model.Count(); i++)
            {
                <tr>
                    <td>
                        <input type="text" value="@Model[i].ID" name="posts[@i].ID" readonly="true" /></td>
                    <td>
                        <input type="text" value="@Model[i].Author.ID" name="posts[@i].Author.ID" readonly="true"/></td>
                    <td>
                        <input type="text" value="@Model[i].DateTime" name="posts[@i].DateTime" /></td>
                    <td>
                        <input type="text" value="@Model[i].Description" name="posts[@i].Description" /></td>
                    <td>
                        <input type="text" value="@Model[i].ImageName" readonly="true"/><input type="file" name="images[@i]" /></td>
                    <td>
                        <div class="ReferenceContainer">
                            <a href="@Url.Action("DeletePost", "AdminHome", new { area = "Admin", id = Model[i].ID })">
                                <div>
                                    @Html.LabelFor(m => action.Delete)
                                </div>
                            </a>
                        </div>

                    </td>
                </tr> 
            }
        </table>
        <div class="ReferenceContainer">
            <a href="javascript:{}" onclick="$('#PostsConsoleContainer>form').submit(); return false;">
                <div>
                    @Html.LabelFor(m => action.Save)
                </div>
            </a>
        </div>
        
        <script type="text/javascript">

            var grid = document.getElementById('AdminConsoleGrid');

            $("#AdminConsoleGrid>thead>tr>th>label").click(function (e) {
                sortGrid($(this.parentElement).index());
            });

            grid.onclick = function (e) {
                if (e.target.tagName != 'TH') return;
                sortGrid(e.target.cellIndex);
            };

            function sortGrid(colNum) {
                var tbody = grid.getElementsByTagName('tbody')[0];

                var rowsArray = [].slice.call(tbody.rows);

                var compare;

                compare = function (rowA, rowB) {
                    return rowA.cells[colNum].innerHTML > rowB.cells[colNum].innerHTML ? 1 : -1;

                }
                rowsArray.sort(compare);

                grid.removeChild(tbody);

                for (var i = 0; i < rowsArray.length; i++) {
                    tbody.appendChild(rowsArray[i]);
                }

                grid.appendChild(tbody);
            }
        </script>
    }
    <div id="AdministrationConsoleAddPostContainer">
        @using (Html.BeginForm("AddPost", "AdminHome", FormMethod.Post, new { area = "Admin", enctype = "multipart/form-data" }))
        {
            <table>
                <thead>
                    <tr>
                        <td>@Html.LabelFor(m => Model[0].Author)</td>
                        <td>@Html.LabelFor(m => Model[0].Description)</td>
                        <td>@Html.LabelFor(m => Model[0].ImageName)</td>
                    </tr>
                </thead>
                <tr>
                    <td>
                        <input data-val="true" data-val-required="@Html.LabelFor(m => messages.FieldRequiredMessage).ToString()" id="AuthorID" name="AuthorID" type="text" value="" class="input-validation-error" /><br />
                        <span class="field-validation-valid" data-valmsg-for="AuthorID" data-valmsg-replace="true"></span>
                    </td>
                    <td>
                        <input type="text" name="Description" /></td>
                    <td>
                        <input data-val="true" data-val-required="@Html.LabelFor(m => messages.FieldRequiredMessage).ToString()" type="file" name="Image" id="Image" class="input-validation-error" /><br />
                        <span class="field-validation-valid" data-valmsg-for="Image" data-valmsg-replace="true"></span></td>
                    <td>
                        <div class="ReferenceContainer">
                            <a href="javascript:{}" onclick="$('#AdministrationConsoleAddPostContainer>form').submit(); return false;">
                                <div>
                                    @Html.LabelFor(m => action.Add)
                                </div>
                            </a>
                        </div>
                </tr>
            </table>
        }
        <script type="text/javascript">
            function ValidateIntValue(event) {
                if (event.keyCode <= 48 || event.keyCode >= 57) {
                    $(AuthorID).val("");
                }
            }
            $(AuthorID).keyup(ValidateIntValue);
        </script>
    </div>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
</div>